resource "local_file" "bike" {
    filename = var.filename
    content = var.content
}

resource "random_pet" "my-pet" {
    prefix = var.prefix[0]
    separator = var.separator
    length = var.length
}

output "pet-name" {
    value = random_pet.my-pet.id
    description = "Record value of pet id which is generated by the random_pet resource "
}